apiVersion: v1
kind: Secret
metadata:
  name: openshift-auth-tls
  namespace: kube-system
type: Opaque
data:
  tls.crt: ${ingress_tls_cert}
  tls.key: ${ingress_tls_key}
  bundle.crt: ${ingress_tls_bundle}
  ca.cert: ${ingress_ca_cert}
